# Site settings

# host: 192.168.1.66

title: "Goals"
description: "I'm John Peart. These are my goals for this year."

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goals.johnpe.art"
author: "John Peart"

# Images and assets
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"

hero-images-path: "/assets/images/hero/"
post-images-path: "/assets/images/posts/"

logo-png: "/assets/images/site/logo.png"
logo-svg: "/assets/images/site/logo.svg"

social-media-image: "/assets/images/site/social-media.png"

touch: "/assets/images/site/touch.png"
pinned: "/assets/images/site/pinned.svg"
pinned-colour: "#009fe3"
logo-favicon-small: "/assets/images/site/favicon-16x16.png"
logo-favicon-medium: "/assets/images/site/favicon-32x32.png"
logo-favicon-large: "/assets/images/site/favicon-96x96.png"

# Social settings
twitter-url: "https://twitter.com/johnpeart" # Twitter handle i.e. joebloggs
twitter-handle: "johnpeart" # Twitter handle i.e. joebloggs

linkedin-url:  "https://www.linkedin.com/in/jrpeart"
linkedin-handle:  "jrpeart"

flickr-url:  "https://www.flickr.com/photos/johnpeart"
flickr-handle:  "johnpeart"

instagram-url:  "https://www.instagram.com/johnpeart"
instagram-handle:  "johnpeart"

github-url:  "https://github.com/johnpeart"
github-handle:  "johnpeart"

# Google settings
google-site-verification: "DaqGCZ6cZIqm7q_nVSnOzjJmFFjbRfW2X7FDzpQDQZk"
google-analytics: "UA-27553664-1" # GA ID code

# Collections

collections:
  goals:
    output: true
    permalink: /:path/
    defaults:
      values:
        layout: goals

# Plugins and build settings

permalink: pretty
markdown: kramdown
future: false
sass:
    sass_dir: _sass

remote_theme: johnpeart/jekyll-theme